#!/usr/bin/env python3
"""
grpc_server.py
--------------
Implements the NetWatchService gRPC server.

This server reads the alerts.jsonl file written by the C++ engine and
serves them over gRPC. It supports both one-shot queries (GetAlerts)
and streaming subscriptions (StreamAlerts).

WHY IS THE SERVER IN PYTHON WHILE THE ENGINE IS IN C++?
  Classic systems design pattern: use C++ where you need raw performance
  (the tight detection loop processing thousands of metrics per second),
  use Python where you need rapid API development. The two processes
  communicate through files, which acts as a simple message queue.
  In production you'd replace the file with Redis pub/sub or Kafka,
  but the architecture is the same.

HOW STREAMING WORKS:
  The StreamAlerts RPC is a Python generator function. gRPC calls it once
  and then the function yields Alert objects one at a time whenever a new
  alert appears. The framework handles all the networking — your code just
  yields the next item when it's ready.
"""

import json
import os
import sys
import time
import threading
from concurrent import futures
from datetime import datetime, timezone

import grpc

# These are generated by protoc — we commit them to the repo
# Run: python -m grpc_tools.protoc -I../proto --python_out=. --grpc_python_out=. ../proto/netwatch.proto
sys.path.insert(0, os.path.dirname(__file__))

try:
    import netwatch_pb2
    import netwatch_pb2_grpc
except ImportError:
    print("[server] Proto stubs not found. Run generate_proto.sh first.")
    sys.exit(1)


ALERTS_FILE = os.environ.get("ALERTS_FILE", "/tmp/netwatch/alerts.jsonl")
GRPC_PORT   = int(os.environ.get("GRPC_PORT", "50051"))

SEVERITY_ORDER = {"WARNING": 0, "MINOR": 1, "MAJOR": 2, "CRITICAL": 3}


def parse_alert_line(line: str) -> dict | None:
    """Parse one line from alerts.jsonl. Returns None on parse error."""
    try:
        return json.loads(line.strip())
    except json.JSONDecodeError:
        return None


def dict_to_alert_proto(d: dict) -> netwatch_pb2.Alert:
    """Convert a parsed JSON dict to a protobuf Alert message."""
    return netwatch_pb2.Alert(
        timestamp      = d.get("timestamp", ""),
        node_id        = d.get("node_id", ""),
        metric         = d.get("metric", ""),
        observed_value = float(d.get("observed_value", 0)),
        z_score        = float(d.get("z_score", 0)),
        severity       = d.get("severity", "WARNING"),
        description    = d.get("description", ""),
    )


def meets_severity(alert_severity: str, min_severity: str) -> bool:
    """Returns True if alert_severity >= min_severity."""
    if not min_severity:
        return True
    return SEVERITY_ORDER.get(alert_severity, 0) >= SEVERITY_ORDER.get(min_severity, 0)


class NetWatchServicer(netwatch_pb2_grpc.NetWatchServiceServicer):
    """
    Implements all four RPC methods defined in netwatch.proto.
    
    In-memory state:
      _alerts: list of all parsed Alert dicts loaded from file
      _nodes:  set of known node IDs (populated as alerts arrive)
      _lock:   threading.RLock protecting both
    
    A background thread (AlertFileWatcher) tails the alerts file and
    appends new items to _alerts. This is the same fan-out pattern used
    by Redis pub/sub: one reader, multiple consumers.
    """

    def __init__(self):
        self._alerts: list[dict] = []
        self._nodes:  set[str]   = set()
        self._lock = threading.RLock()

        # New-alert condition variable — lets StreamAlerts sleep efficiently
        # instead of spinning in a tight loop
        self._new_alert_event = threading.Event()

        # Load existing alerts from file on startup
        self._load_existing_alerts()

        # Start background watcher
        t = threading.Thread(target=self._watch_alerts_file, daemon=True)
        t.start()
        print(f"[server] Loaded {len(self._alerts)} existing alerts. Watching for new ones.")

    def _load_existing_alerts(self):
        if not os.path.exists(ALERTS_FILE):
            return
        with open(ALERTS_FILE, "r") as f:
            for line in f:
                d = parse_alert_line(line)
                if d:
                    self._alerts.append(d)
                    self._nodes.add(d.get("node_id", ""))

    def _watch_alerts_file(self):
        """
        Background thread: tail-follows the alerts file.
        Wakes up streaming subscribers via _new_alert_event.
        """
        while True:
            if not os.path.exists(ALERTS_FILE):
                time.sleep(0.5)
                continue

            with open(ALERTS_FILE, "r") as f:
                # Seek to end — we already loaded history
                f.seek(0, 2)
                while True:
                    line = f.readline()
                    if line:
                        d = parse_alert_line(line)
                        if d:
                            with self._lock:
                                self._alerts.append(d)
                                self._nodes.add(d.get("node_id", ""))
                            # Wake up all StreamAlerts subscribers
                            self._new_alert_event.set()
                            self._new_alert_event.clear()
                    else:
                        time.sleep(0.1)

    # ── GetAlerts (unary) ──────────────────────────────────────────────────
    def GetAlerts(self, request, context):
        with self._lock:
            alerts = list(self._alerts)

        # Filter by node
        if request.node_id:
            alerts = [a for a in alerts if a.get("node_id") == request.node_id]

        # Filter by severity
        if request.min_severity:
            alerts = [a for a in alerts if meets_severity(a.get("severity",""), request.min_severity)]

        # Sort newest first
        alerts.sort(key=lambda a: a.get("timestamp", ""), reverse=True)

        # Apply limit
        total = len(alerts)
        if request.limit and request.limit > 0:
            alerts = alerts[:request.limit]

        return netwatch_pb2.GetAlertsResponse(
            alerts=[dict_to_alert_proto(a) for a in alerts],
            total=total,
        )

    # ── StreamAlerts (server-streaming) ───────────────────────────────────
    def StreamAlerts(self, request, context):
        """
        Yields alerts to the client as they arrive.
        The client stays connected; we push each new alert immediately.
        
        This is real-time push — no polling, no delay.
        """
        with self._lock:
            # Send all historical alerts first (so client gets context)
            history = [
                a for a in self._alerts
                if (not request.node_id or a.get("node_id") == request.node_id)
                and meets_severity(a.get("severity",""), request.min_severity)
            ]
            last_seen_index = len(self._alerts)

        for alert in history:
            if not context.is_active():
                return
            yield dict_to_alert_proto(alert)

        # Then stream new alerts as they arrive
        while context.is_active():
            self._new_alert_event.wait(timeout=5.0)  # wake up on new alert or every 5s

            with self._lock:
                new_alerts = self._alerts[last_seen_index:]
                last_seen_index = len(self._alerts)

            for alert in new_alerts:
                if not context.is_active():
                    return
                if request.node_id and alert.get("node_id") != request.node_id:
                    continue
                if not meets_severity(alert.get("severity",""), request.min_severity):
                    continue
                yield dict_to_alert_proto(alert)

    # ── GetNodes (unary) ──────────────────────────────────────────────────
    def GetNodes(self, request, context):
        with self._lock:
            nodes = sorted(self._nodes)
        return netwatch_pb2.GetNodesResponse(node_ids=nodes)

    # ── HealthCheck (unary) ───────────────────────────────────────────────
    def HealthCheck(self, request, context):
        return netwatch_pb2.HealthResponse(
            ok=True,
            message=f"OK — {len(self._alerts)} alerts indexed, "
                    f"{len(self._nodes)} nodes tracked, "
                    f"alerts file: {'present' if os.path.exists(ALERTS_FILE) else 'missing'}"
        )


def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    netwatch_pb2_grpc.add_NetWatchServiceServicer_to_server(
        NetWatchServicer(), server
    )
    listen_addr = f"[::]:{GRPC_PORT}"
    server.add_insecure_port(listen_addr)
    server.start()
    print(f"[server] gRPC server listening on {listen_addr}")
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
